MVC5OnlineTicariOtomasyon/Models/Classes/Personel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVC5OnlineTicariOtomasyon.Models.Classes
{
	public class Personel
	{
		[Key]
		public int PersonelId { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(30)]
		public string PersonelAd { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(30)]
		public string PersonelSoyad { get; set; }
		[Column(TypeName = "Varchar")]
		[StringLength(250)]
		public string PersonelGorsel { get; set; }
		public virtual Departman Departman { get; set; }
		public int Departmanid { get; set; }
		public ICollection<SatisHareket> SatisHarekets { get; set; }
	}
}

MVC5OnlineTicariOtomasyon/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5OnlineTicariOtomasyon.Models.Classes;
namespace MVC5OnlineTicariOtomasyon.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        Context c = new Context();
        public ActionResult Index()
        {
            var degerler = c.Personels.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            return View();
        }
         [HttpPost]
         public ActionResult PersonelEkle(Personel p)
        {
            c.Personels.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult PersonelSil(int id)
        {
           
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Departmans.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.DepartmanAd,
                                               Value = x.Departmanid.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var prs = c.Personels.Find(id);
            return View("PersonelGetir", prs);
            
        }

        public ActionResult PersonelGuncelle (Personel p)
		{
            var persn = c.Personels.Find(p.PersonelId);
            persn.PersonelAd = p.PersonelAd;
            persn.PersonelSoyad = p.PersonelSoyad;
            persn.PersonelGorsel = p.PersonelGorsel;
            persn.Departmanid = p.Departmanid;
            c.SaveChanges();
            return RedirectToAction("Index");

        }

    }

}

MVC5OnlineTicariOtomasyon/Views/Personel/Index.cshtml
@using MVC5OnlineTicariOtomasyon.Models.Classes
@model List<Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Personeller</h2>

<table class="table table-bordered">

    <tr>
        <td> ID</td>
        <td> Personel Adı</td>
        <td> Soyadı</td>
        <td> Görsel</td>
        <td> Departman</td>
        <td>Sil</td>
        <td>Güncelle</td>
        <td>Detaylar</td>
    </tr>

    @foreach (var u in Model)
    {
<tr>
    <td>@u.PersonelId</td>
    <td>@u.PersonelAd</td>
    <td>@u.PersonelSoyad</td>
    <td>@u.PersonelGorsel</td>
    <td>@u.Departman.DepartmanAd</td>

    <td>  <a href="/Personel/PersonelSil/" class="btn btn-danger">Sil</a></td>
    <td>  <a href="/Personel/PersonelGetir/@u.PersonelId" class="btn btn-warning ">Güncelle</a></td>
    <td>  <a href="/Departman/DepartmanSatis/@u.PersonelId" class="btn btn-default" style="background-color:lightcoral">Detaylar</a></td>


</tr>

        }

    </table>
<a href="/Personel/PersonelEkle" class="btn btn-primary"> Departman Ekle</a></a>

MVC5OnlineTicariOtomasyon/Views/Personel/PersonelEkle.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Personel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>PersonelEkle</h2>
<form class="form-group" method="post">
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })
    <br />

    @Html.LabelFor(x => x.Departman.Departmanid)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })



    <button class="btn btn-info">Kaydet </button>

</form>

MVC5OnlineTicariOtomasyon/Views/Personel/PersonelGetir.cshtml
@model MVC5OnlineTicariOtomasyon.Models.Classes.Personel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>PersonelGetir</h2>

<h2>Cari Bilgisi Güncelle</h2>

<br />
@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{

<div class="form-group">
    @Html.HiddenFor(x => x.PersonelId)
    @Html.LabelFor(x => x.PersonelAd)
    @Html.TextBoxFor(x => x.PersonelAd, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.PersonelSoyad)
    @Html.TextBoxFor(x => x.PersonelSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.PersonelSoyad, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.PersonelGorsel)
    @Html.TextBoxFor(x => x.PersonelGorsel, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.Departman.Departmanid)
    @Html.DropDownListFor(x => x.Departmanid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })

    <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
    
</div>
}